### PR TITLE
Reorganize remote_settings directory structure

### PR DESCRIPTION
**Pull request by nordzilla**
As someone who is new to Python, I was chatting with Eemeli about how I was having difficulties getting the Python directory structure to match something that I liked, imports failing etc. 

He helped me out and submitted a quick PR to help me achieve what I wanted. That's the first commit.

After that I just made some miscellaneous updates surrounding the script, such as running the tests via `discover` in the `unittest` module, as well as running the `remote_settings` script using the `-m` flag.

### CODE REVIEW

**Comment by nordzilla** [comment]
How odd. It looks like this patch is getting the `eval` updates from my previous PR to reorganize the `dev` and `prod` directories to match Firefox. 

It seems like we're in some sort of one-step-behind cadence?

**Review by eu9ene — COMMENTED** [review]
Usually we split tests to a separate directory in the root and set `PYTHONPATH=<root>`or run something like `pytest tests`, then your imports would look like `from remote_settings.client import print_info`.

As far as I know it's not the best practice to use relative imports in general because you can easily control where the root is with `PYTHONPATH` and always specify absolute import.  See example here https://github.com/mozilla/firefox-translations-training/blob/main/tests/test_data_importer.py or here https://github.com/Pocket/recommendation-api/blob/main/tests/functional/data_providers/test_corpus_api_client.py

**Comment by nordzilla** [comment]
@eu9ene 

I've reworked the commit stack according to your feedback.

**Commits diff**
image

**Review by eu9ene — APPROVED** [review]
Looks good now!

**Pull request merged**
